version: 2.1
orbs:
  report_deploy: opslevel/report_deploy@1.0.0

filters: &filters
  tags:
    only: /.*/

# define the job to report a deploy here
jobs:
  run-report-deploy:
    docker:
      - image: 'public.ecr.aws/opslevel/cli:v2024.3.15'
    steps:
      - checkout
      - report_deploy/report:
          deployer_email: "robot@opslevel.com"
          deployer_name: "OpsLevel Robot"
          description: "hello world - this deploy event was sent for the circleci orb demo"
          environment: "production"
          service: "opslevel_circleci_orb"

# add the workflow to run that job here
workflows:
  test-deploy:
    jobs:
      - run-report-deploy:
          # this context is used so that there is an INTEGRATION_URL environment variable.
          context: circular_integration_context
          filters: *filters
